# Generated by Django 4.1.2 on 2025-02-12 03:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_passwordresetrequest_delete_passwordreset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blogs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('Uncategorized', 'Uncategorized'), ('Technology', 'Technology'), ('Programming', 'Programming'), ('Business', 'Business'), ('Marketing', 'Marketing'), ('Health', 'Health'), ('Travel', 'Travel'), ('Food', 'Food'), ('Fashion', 'Fashion'), ('Sports', 'Sports'), ('Entertainment', 'Entertainment'), ('Lifestyle', 'Lifestyle'), ('Gaming', 'Gaming'), ('Music', 'Music'), ('Movies', 'Movies'), ('TV', 'TV'), ('Books', 'Books'), ('News', 'News'), ('Politics', 'Politics'), ('Science', 'Science'), ('Education', 'Education'), ('Environment', 'Environment'), ('History', 'History'), ('Art', 'Art'), ('Design', 'Design'), ('Photography', 'Photography'), ('Economics', 'Economics'), ('Finance', 'Finance'), ('Law', 'Law'), ('Religion', 'Religion'), ('Philosophy', 'Philosophy')], default='Uncategorized', max_length=100),
        ),
        migrations.AlterField(
            model_name='blog',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_blogs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blog',
            name='publish_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.blog'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_verification', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_resets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
