# Generated by Django 4.1.2 on 2025-02-24 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_profile_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_verified',
        ),
    ]
